-- Migration: Shift Checklist System (Consolidated)
-- Date: 2026-03-23
-- Description: Links checklists to shifts via junction table and adds period targeting.

-- 1. Ensure Shift Period Enum exists (Morning, Day, Night, All)
DO $$ BEGIN
    CREATE TYPE public.shift_period_enum AS ENUM ('morning', 'day', 'night', 'all');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Update house_calendar_events to support period-based color coding
ALTER TABLE public.house_calendar_events
ADD COLUMN IF NOT EXISTS target_shift public.shift_period_enum NOT NULL DEFAULT 'all';

-- 3. Update checklist_schedules to support period-based generation
ALTER TABLE public.checklist_schedules
ADD COLUMN IF NOT EXISTS target_shift public.shift_period_enum NOT NULL DEFAULT 'all';

-- 4. Create the junction table for shift-specific assignments
CREATE TABLE IF NOT EXISTS public.shift_assigned_checklists (
    id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    shift_id uuid NOT NULL REFERENCES public.staff_shifts(id) ON DELETE CASCADE,
    checklist_id uuid NOT NULL REFERENCES public.house_checklists(id) ON DELETE CASCADE,
    assignment_title text NOT NULL, -- e.g. "Start of Shift", "Medication Round"
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    
    -- Ensure a checklist isn't assigned to the same shift twice with the same role
    UNIQUE(shift_id, checklist_id, assignment_title)
);

-- 5. Enable RLS
ALTER TABLE public.shift_assigned_checklists ENABLE ROW LEVEL SECURITY;

-- 6. Create RLS Policies
DROP POLICY IF EXISTS "Users can view shift assignments for their houses" ON public.shift_assigned_checklists;
CREATE POLICY "Users can view shift assignments for their houses"
    ON public.shift_assigned_checklists FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Admins can manage shift assignments" ON public.shift_assigned_checklists;
CREATE POLICY "Admins can manage shift assignments"
    ON public.shift_assigned_checklists FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- 7. Add reference to junction table in submissions
ALTER TABLE public.house_checklist_submissions
ADD COLUMN IF NOT EXISTS shift_assignment_id uuid REFERENCES public.shift_assigned_checklists(id) ON DELETE SET NULL;

-- 8. Add comments for documentation
COMMENT ON COLUMN public.house_calendar_events.target_shift IS 'Target shift period for this event (Morning, Day, Night, All)';
COMMENT ON COLUMN public.checklist_schedules.target_shift IS 'Default target shift period for events generated by this schedule';
COMMENT ON TABLE public.shift_assigned_checklists IS 'Junction table linking specific checklist templates to rostered shifts with custom titles';
