import { ReactNode } from 'react';
import { toAbsoluteUrl } from '@/lib/helpers';
import { cn } from '@/lib/utils';
import { format } from 'date-fns';
import { useAuth } from '@/auth/context/auth-context';

interface PrintableReportProps {
  title: string;
  subtitle?: string;
  parameters?: Record<string, string>;
  children: ReactNode;
  className?: string;
}

export function PrintableReport({ 
  title, 
  subtitle, 
  parameters, 
  children, 
  className 
}: PrintableReportProps) {
  const { user } = useAuth();
  const generationDate = format(new Date(), 'dd MMMM yyyy HH:mm');

  return (
    <div className={cn("printable-report-container bg-white", className)}>
      {/* Print-specific Styles */}
      <style>
        {`
          @media print {
            @page {
              size: A4;
              margin: 15mm;
            }
            body {
              background: white !important;
              -webkit-print-color-adjust: exact;
            }
            .no-print {
              display: none !important;
            }
            .printable-report-container {
              width: 100% !important;
              max-width: 100% !important;
              margin: 0 !important;
              padding: 0 !important;
              box-shadow: none !important;
              border: none !important;
            }
            /* Force breaks where needed */
            .page-break {
              page-break-before: always;
            }
            .printable-report-preview {
              max-width: 100% !important;
              margin: 0 !important;
              padding: 0 !important;
              box-shadow: none !important;
              border-radius: 0 !important;
              min-height: auto !important;
            }
          }
          
          /* Screen preview styles */
          .printable-report-preview {
            max-width: 210mm;
            margin: 0 auto 2rem auto;
            padding: 10mm 15mm;
            box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1);
            border-radius: 4px;
            min-height: 297mm;
          }
        `}
      </style>

      <div className="printable-report-preview bg-white text-gray-900 font-sans">
        {/* Header / Letterhead */}
        <div className="flex justify-between items-start border-b-2 border-gray-100 pb-6 mb-6">
          <div className="flex flex-col gap-3">
            <img 
              src={toAbsoluteUrl('/media/app/default-logo.png')} 
              alt="InsideCare Logo" 
              className="h-12 w-auto object-contain"
            />
            <div>
              <h1 className="text-xl font-black tracking-tight text-gray-900 uppercase">
                {title}
              </h1>
              {subtitle && (
                <p className="text-sm text-gray-500 font-medium mt-0.5">
                  {subtitle}
                </p>
              )}
            </div>
          </div>
          
          <div className="text-right flex flex-col gap-2">
            <div className="bg-gray-50 p-3 rounded-lg border border-gray-100 inline-block text-left min-w-[220px]">
              <div className="text-[9px] uppercase font-bold text-gray-400 tracking-wider mb-1.5">Report Metadata</div>
              <div className="grid grid-cols-2 gap-x-3 gap-y-0.5 text-[11px]">
                <span className="text-gray-500">Generated By:</span>
                <span className="font-semibold text-gray-900">{user?.staff_name || user?.fullname || 'System User'}</span>
                
                <span className="text-gray-500">Date:</span>
                <span className="font-semibold text-gray-900">{generationDate}</span>
                
                {parameters && Object.entries(parameters).map(([key, value]) => (
                  <div key={key} className="contents">
                    <span className="text-gray-500">{key}:</span>
                    <span className="font-semibold text-gray-900">{value}</span>
                  </div>
                ))}
              </div>
            </div>
            <div className="text-[9px] text-gray-400 uppercase tracking-widest font-bold mt-1">
              InsideCare Operations • Confidential
            </div>
          </div>
        </div>

        {/* Content Area */}
        <div className="flex flex-col gap-6">
          {children}
        </div>

        {/* Footer */}
        <div className="mt-10 pt-6 border-t border-gray-100 text-center">
          <p className="text-[9px] text-gray-400 leading-relaxed max-w-md mx-auto">
            This document is confidential and contains sensitive information. Unauthorized reproduction or distribution is strictly prohibited. 
            Generated from the InsideCare Management System.
          </p>
          <div className="mt-3 text-[9px] text-gray-300 font-mono">
            REF: IC-REP-{Date.now().toString(36).toUpperCase()}
          </div>
        </div>
      </div>
    </div>
  );
}
